<a href="/usuarios/test" > Usuarios </a>
<a href="/espectaculos/test" > Espectaculo </a>
<a href="/entrada/test" > Entradas </a>
<br><br><br>
<form method="post" action="/sesion/post/">
    <h3><label>SESIÓN</label></h3><br>
    <label>Fecha y hora de inicio:</label>
    <input type="datetime" name="fecha_hora_inicio"/> <br>
    <label>Duracion</label>
    <input type="text" name="duracion"/><br>
    <label>Capacidad</label>
    <input type="text" name="capacidad"/><br>
    <label>Precio</label>
    <input type="text" name="precio"/><br>
    <label>Iva</label>
    <input type="text" name="iva"/><br>
    <label>Api key</label>
    <input type="text" name="api_key"/><br>
    <label>Id espectaculo</label>
    <input type="text" name="id_espectaculo"/><br>
    <h3><label>Datos Recinto</label></h3><br>
    <label>Direccion</label>
    <input type="text" name="direccion"/><br>
    <label>Ciudad</label>
    <input type="text" name="ciudad"/><br>
    <label>Provincia</label>
    <input type="text" name="provincia"/><br>
    <label>Pais</label>
    <input type="text" name="pais"/><br>

    <input type="submit" value="Enviar"/><br>
</form>