<a href="/usuarios/test" > Usuarios </a>
<a href="/sesion/test" > Sesion </a>
<a href="/entrada/test" > Entradas </a>
<br><br><br>
<form method="post" action="/espectaculos/post/" >
    <h3><label>ESPECTACULOS: </label></h3><br>
    <label>Titulo</label>
    <input type="text" name="titulo"/> <br>

    <label>Descripcion</label>
    <input type="text" name="descripcion"/><br>

    <label>Url</label>
    <input type="text" name="url"/><br>
    
    <label>Api Key</label>
    <input type="text" name="api_key"/><br>


    <input type="submit" value="Enviar"/><br>
</form>