<a href="/usuarios/test" > Usuarios </a>
<a href="/espectaculos/test" > Espectaculo </a>
<a href="/sesion/test" > Sesion </a>
<br><br><br>
<form method="post" action="/entrada/post/">
    
    <h3><label>ENTRADAS: </label></h3><br>
    <label>Id espectaculo</label>
    <input type="text" name="id_espectaculo"/><br>
    <label>Sesion: </label>
    <input type="text" name="id_sesion"/> <br>
    <label>Api key</label>
    <input type="text" name="api_key"/><br
    <label>Numero Entradas</label>
    <input type="text" name="numero_entradas"/><br>
    <h3><label>Datos Comprador</label></h3><br>
    <label>Nombre</label>
    <input type="text" name="nombre"/><br>
    <label>Apellidos</label>
    <input type="text" name="apellidos"/><br>
    <label>DNI</label>
    <input type="text" name="dni"/><br>
    <label>Email</label>
    <input type="text" name="email"/><br>
    <label>Telefono</label>
    <input type="text" name="telefono"/><br>
    
    <input type="submit" value="Enviar"/><br>
</form>