<a href="/sesion/test" > Sesion </a>
<a href="/espectaculos/test" > Espectaculo </a>
<a href="/entrada/test" > Entradas </a>
<br><br><br>
<form method="post" action="/usuarios/">
    <h3><label>USUARIOS: </label></h3><br>
    <label>User</label>
    <input type="text" name="usuario"/> <br>
    <label>Contraseña</label>
    <input type="password" name="password"/><br>
    <label>Dni</label>
    <input type="text" name="dni"/><br>
    <label>Email</label>
    <input type="text" name="email"/><br>
    <label>Telefono</label>
    <input type="text" name="telefono"/><br>
    <label>Cif</label>
    <input type="text" name="cif"/><br>
    <label>Nombre Empresa</label>
    <input type="text" name="nombre_empresa"/><br>

    <input type="submit" value="Enviar"/><br>
</form>